import Head from "next/head";
import axios from "axios";
import Navbar from "@/components/navbar";
import Carousel from "@/components/carousel";
import Sidebar from "@/components/sidebar";
import Card from "@/components/card";

export default function Home({ data }: any) {
  return (
    <>
      <Head>
        <title>Webflix Uzbekistan Watch TV Shows Online</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.jpg" />
      </Head>
      <header>
        <Navbar />
      </header>
      <main className="container pt-[70px]">
        <div className="flex gap-4">
          <div className="hidden md:block lg:block">
            <Sidebar />
          </div>
          <div className="w-full">
            <div className="flex flex-col gap-4">
              <Carousel items={data.slice(2, 7)} />
              <div className="text-white grid lg:grid-cols-5 sm:grid-cols-3 grid-cols-2 gap-4 md:grid-cols-4">
                {data.map((item: any) => (
                  <Card
                    poster=""
                    title=""
                    year={3}
                    id={3}
                    key={item.id}
                    data={item}
                  />
                ))}
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  const data = await axios(
    "https://api.cinerama.uz/api-test/movie-list?page=1&items=20"
  );
  console.log(data.data);

  return {
    props: {
      data: data.data.data.movieList,
    },
  };
};
